# Generated by Django 3.0.1 on 2020-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20200518_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='owner',
            field=models.CharField(default='soni', max_length=100),
        ),
        migrations.AlterField(
            model_name='emails',
            name='mail',
            field=models.CharField(max_length=100),
        ),
    ]
