# Generated by Django 3.0.1 on 2020-05-18 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_remove_emails_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='mail',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('/\\S+@\\S+\\.\\S+/', message='enter a valid e-mail')]),
        ),
    ]
