# Generated by Django 3.0.1 on 2020-05-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20200518_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='mess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('subject', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='emails',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
